site_name: System Principles

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Principles:
    - Design: principles/design.md
    - Polymorphism: principles/polymorphism.md
    - Projects: principles/projects.md
    - Testing: principles/testing.md
    - Dependencies: principles/dependencies.md
    - Translators: principles/translators.md
    - Mocking: principles/mocking.md
